[package]
name = "game_ai"
version = "0.1.0"
authors = ["Daniele Bianchin <bianchin.daniele.b@gmail.com>"]
edition = "2018"

[lib]
name = "game_ai"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "move_generator"
path = "src/bin/move_generator.rs"

[dependencies]
num-traits = "0.2.14"
rand = "0.8.3"